name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm cache clean --force
        npm install
      working-directory: CampusReactApp/frontend

    - name: Add .env to Skip Preflight
      run: echo "SKIP_PREFLIGHT_CHECK=true" > .env
      working-directory: CampusReactApp/frontend

    - name: Run tests
      run: npm test
      working-directory: CampusReactApp/frontend


<<<<<<< HEAD
    - name: Lint code
      run: npm run lint  
=======
  
>>>>>>> cbaeadb69664be713d49558df22b6f02c48f3384
